<div class="well well-small">
    <div class="row-fluid">
        <div class="span5">
            <div id="myCarousel" class="carousel slide cntr">
                <div class="carousel-inner">
                    <div class="item active">
                        <a href="#"> <img src="/assets/product/<?php echo trim($product['image'],"/");?>" alt="" style="width:100%"></a>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            </div>
        </div>
        <div class="span7">
            <h3><?php echo h($product['name']);?></h3>
            <hr class="soft"/>

            <form class="form-horizontal qtyFrm">
                <div class="control-group">
                    <label class="control-label"><span>$<?php echo number_format($product['price'],2);?></span></label>
                    <div class="controls">
                        <input type="number" class="span6" placeholder="Qty." value="1">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label"><span>Color</span></label>
                    <div class="controls">
                        <select class="span11">
                            <option>Red</option>
                            <option>Purple</option>
                            <option>Pink</option>
                            <option>Red</option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label"><span>Materials</span></label>
                    <div class="controls">
                        <select class="span11">
                            <option>Material 1</option>
                            <option>Material 2</option>
                            <option>Material 3</option>
                            <option>Material 4</option>
                        </select>
                    </div>
                </div>
                <h4>100 items in stock</h4>
                <p>Nowadays the lingerie industry is one of the most successful business spheres.
                    Nowadays the lingerie industry is one of ...
                <p>
                    <button type="submit" class="shopBtn"><span class=" icon-shopping-cart"></span> Add to cart</button>
            </form>
        </div>
    </div>
    <hr class="softn clr"/>


    <ul id="productDetail" class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Product Details</a></li>
        <li class=""><a href="#profile" data-toggle="tab">Related Products </a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Acceseries <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#cat1" data-toggle="tab">Category one</a></li>
                <li><a href="#cat2" data-toggle="tab">Category two</a></li>
            </ul>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content tabWrapper">
        <div class="tab-pane fade active in" id="home">
            <h4>Product Information</h4>
            <table class="table table-striped">
                <tbody>
                <tr class="techSpecRow"><td class="techSpecTD1">Color:</td><td class="techSpecTD2">Black</td></tr>
                <tr class="techSpecRow"><td class="techSpecTD1">Style:</td><td class="techSpecTD2">Apparel,Sports</td></tr>
                <tr class="techSpecRow"><td class="techSpecTD1">Season:</td><td class="techSpecTD2">spring/summer</td></tr>
                <tr class="techSpecRow"><td class="techSpecTD1">Usage:</td><td class="techSpecTD2">fitness</td></tr>
                <tr class="techSpecRow"><td class="techSpecTD1">Sport:</td><td class="techSpecTD2">122855031</td></tr>
                <tr class="techSpecRow"><td class="techSpecTD1">Brand:</td><td class="techSpecTD2">Shock Absorber</td></tr>
                </tbody>
            </table>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
            <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>

        </div>
    </div>
</div>
