<div class="well well-small">
    <h1>Check Out <small class="pull-right"> <?php echo count($cartItems);?> Item(s) are in the cart </small></h1>
    <hr class="soften"/>
    <form action="/cart/update" method="POST" id="cartForm">
    <table class="table table-bordered table-condensed">
        <thead>
        <tr>
            <th>Product</th>
            <th>Description</th>
            <th>Unit price</th>
            <th>Qty </th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        
        <?php $total = 0; foreach($cartItems as $id=>$item): $product = $item['product']; $qty = $item['qty']; $total += $product['price']*$qty; ?>
        <tr>
            <td><img width="75" src="/assets/product/<?php echo trim($product['image'],"/");?>" alt=""></td>
            <td><?php echo h($product['name']); ?></td>
            <td>$<?php echo number_format($product['price'],2);?></td>
            <td>
                <input class="span1" style="max-width:34px" placeholder="1" id="itemQty<?php echo $id;?>"  name="qty[<?php echo $id;?>]" size="16" type="text" value="<?php echo $qty;?>" onchange="hideCheckout();">
                <div class="input-append">
                    <button class="btn btn-mini" type="button" onclick="cartUpdate(<?php echo $id;?>, -1);">-</button>
                    <button class="btn btn-mini" type="button" onclick="cartUpdate(<?php echo $id;?>, +1);">+</button>
                    <button class="btn btn-mini btn-danger" type="button" onclick="cartUpdate(<?php echo $id;?>, 0);"><span class="icon-remove"></span></button>
                </div>
            </td>
            <td class="alignR">$<?php echo number_format($product['price']*$qty,2);?></td>
        </tr>
        <?php endforeach; ?>
        <?php if($cartItems): ?>
        <tr>
            <td colspan="3">Total products:	</td>
            <td>
                <button class="btn btn-danger" type="submit" disabled="disabled" id="btnUpdateCart">Update cart</button>
                <button class="btn" type="reset"  disabled="disabled"  id="btnResetCart">Reset qty</button>
            </td>
            <td  class="alignR">$<?php echo number_format($total,2);?></td>
        </tr>
        <?php endif; ?>

        </tbody>
    </table>
        <br>
    </form>
</div>
<?php if(empty($loggedUser) ||empty($cartItems)): ?>
<div class="well well-small">
    <a href="/" class="shopBtn btn-large" onclick="history.back(); return false;"><span class="icon-arrow-left"></span> Continue Shopping </a>
    <?php if(empty($loggedUser)):?>
    <a href="/user/login/toOrder" class="shopBtn btn-large pull-right">Login (to place order) <span class="icon-arrow-right"> </a>
    <?php endif; ?>
</div>
<?php else: ?>
<form action="/cart/order" method="POST">
<div class="row" id="checkoutForm">
    <div class="span6">
        <div class="well">
            <h5>Billing address</h5>
                <div class="control-group">
                    <label class="control-label" for="billingName">Name</label>
                    <div class="controls">
                        <input name="billing[name]" id="billingName"  class="span3 required"  type="text" placeholder="Name" value="<?php echo h($billing['name'] ?? $loggedUser['name'] ?? '');?>">
                    </div>
                    <label class="control-label" for="billingPhone">Phone</label>
                    <div class="controls">
                        <input name="billing[phone]" id="billingPhone"  class="span3 required"  type="text" placeholder="Phone" value="<?php echo h($billing['phone'] ?? $loggedUser['phone'] ?? '');?>">
                    </div>
                    <label class="control-label" for="billingEmail">Email</label>
                    <div class="controls">
                        <input name="billing[email]" id="billingEmail"  class="span3 required"  type="text" placeholder="Email" value="<?php echo h($billing['email'] ?? $loggedUser['email'] ?? '');?>">
                    </div>
                    <label class="control-label" for="billingAddress">Address (street, no, building)</label>
                    <div class="controls">
                        <input name="billing[address]" id="billingAddress"  class="span3 required"  type="text" placeholder="Address" value="<?php echo h($billing['address'] ?? '');?>">
                    </div>
                    <label class="control-label" for="billingCity">City</label>
                    <div class="controls">
                        <input name="billing[city]" id="billingCity"  class="span3 required"  type="text" placeholder="City" value="<?php echo h($billing['city'] ?? '');?>">
                    </div>
                    <label class="control-label" for="billingState">State/province</label>
                    <div class="controls">
                        <input name="billing[state]" id="billingState"  class="span3"  type="text" placeholder="State" value="<?php echo h($billing['state'] ?? '');?>">
                    </div>                    
                </div>
        </div>
    </div>
    <div class="span6">
        <div class="well">
            <h5>Shipping address (do not fill if same as billing)</h5>
            <div class="control-group">
                <label class="control-label" for="shippingName">Name</label>
                <div class="controls">
                    <input name="shipping[name]" id="shippingName"  class="span3"  type="text" placeholder="Name" value="<?php echo h($shipping['name'] ?? '');?>">
                </div>
                <label class="control-label" for="shippingPhone">Phone</label>
                <div class="controls">
                    <input name="shipping[phone]" id="shippingPhone"  class="span3"  type="text" placeholder="Phone" value="<?php echo h($shipping['phone'] ?? '');?>">
                </div>
                <label class="control-label" for="shippingEmail">Email</label>
                <div class="controls">
                    <input name="shipping[email]" id="shippingEmail"  class="span3"  type="text" placeholder="Email" value="<?php echo h($shipping['email'] ?? '');?>">
                </div>                
                <label class="control-label" for="shippingAddress">Address (street, no, building)</label>
                <div class="controls">
                    <input name="shipping[address]" id="shippingAddress"  class="span3"  type="text" placeholder="Address" value="<?php echo h($shipping['address'] ?? '');?>">
                </div>
                <label class="control-label" for="shippingCity">City</label>
                <div class="controls">
                    <input name="shipping[city]" id="shippingCity"  class="span3"  type="text" placeholder="City" value="<?php echo h($shipping['city'] ?? '');?>">
                </div>
                <label class="control-label" for="shippingState">State/province</label>
                <div class="controls">
                    <input name="shipping[state]" id="shippingState"  class="span3"  type="text" placeholder="State" value="<?php echo h($shipping['state'] ?? '');?>">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="well well-small">
    <a href="/" class="shopBtn btn-large" onclick="history.back(); return false;"><span class="icon-arrow-left"></span> Continue Shopping </a>
    <button type="submit" class="shopBtn btn-large pull-right" id="checkoutButton" onclick="return canCheckout();">Place Order <span class="icon-arrow-right"></span></button>
</div>

</form>
<?php endif; ?>

<script type="text/javascript">
    function cartUpdate(id, qty) {
        var qtyEl = document.getElementById('itemQty' + id);
        var curQty = qtyEl.value;

        if (qty < 0) {
            if (curQty > 0) {
                qtyEl.value--;
            }
        } else {
            if (qty > 0) {
                qtyEl.value++;
            } else {
                qtyEl.value = 0;
            }
        }
        hideCheckout();
    }
    
    function hideCheckout() {
        document.getElementById('btnUpdateCart').disabled = false;
        document.getElementById('btnResetCart').disabled = false;
        document.getElementById('checkoutForm').remove();
    }
    
    function canCheckout() {
        if (!document.getElementById('checkoutForm')) {
            document.getElementById('checkoutButton').remove();
            alert("Please update cart");
            return false;
        }
        var els = document.getElementsByClassName("required");
        var err = [];
        
        if(els.length) {
            for (var i = 0; i < els.length; i++) {
                if(!els[i].value) {
                    err.push(els[i].id);
                }
            }
            if (err.length) {
                alert("Please fill all required field(s): " + err.join(", "));
                return false;
            }
        }
      return true;
        
    }
</script>