<?php
/** 
 * @var string $title
 * @var array $category  
 */
?>

<div class="container">
    <h3><?php echo h($title);?></h3>
    <form action="/admin/category/<?php echo empty($category['id'])?'new':"edit/{$category['id']}";?>" method="post">
        <div class="form-group row mb-1">
            <label for="categoryName" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="categoryName" placeholder="Category name" name="category[name]" value="<?php echo h($category['name']);?>">
            </div>
        </div>
        <div class="form-group row mb-1">
            <label for="categoryPosition" class="col-sm-2 col-form-label">Position</label>
            <div class="col-sm-1">
                <input type="text" class="form-control" id="categoryPosition" placeholder="Position" name="category[position]" value="<?php echo h($category['position']);?>">
            </div>
        </div>
        <div class="form-group row mb-1">
            <span class="col-sm-2"><a href="/admin/category/list">cancel</a></span>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Save category</button>
            </div>
        </div>
    </form>
</div>
