<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Twitter Bootstrap shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet"/>
    <!-- Customize styles -->
    <link href="/assets/style.css" rel="stylesheet"/>
    <!-- font awesome styles -->
    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
    <link href="/assets/font-awesome/css/font-awesome-ie7.min.css" rel="stylesheet">
    <![endif]-->

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons -->
    <link rel="shortcut icon" href="/assets/ico/favicon.ico">
</head>
<body>

<!--
Lower Header Section 
-->
<div class="container">
    <div id="gototop"> </div>
    <header id="header">
        <div class="row topNav">
            <div class="span4">
                <h1>
                    <a class="logo" href="/"><span>Twitter Bootstrap ecommerce template</span>
                        <img src="/assets/img/logo-bootstrap-shoping-cart.png" alt="bootstrap sexy shop">
                    </a>
                </h1>
            </div>
            <div class="span8 alignR align-middle">
                <a href="/"> <span class="icon-home"></span> Home</a>
                <?php if(empty($loggedUser)): ?>
                    <a href="/user/login"><span class="icon-signin"></span> Login</a>
                    <a href="/user/register"><span class="icon-edit"></span> Free Register </a>
                <?php else: ?>
                    <?php if($loggedUser['admin']>0): ?>
                        <a href="/admin/dashboard"><span class="icon-edit"></span> ADMIN AREA</a>
                    <?php endif; ?>
                    <a href="/user/dashboard"><span class="icon-user"></span> My Account</a>
                    <a href="/user/logout"><span class="icon-signout"></span> Logout</a>
                <?php endif; ?>
                <a href="/page/contact"><span class="icon-envelope"></span> Contact us</a>
                <?php
                    $totalCartItems = 0; 
                    $cntCartItems = 0;
                    foreach($cartItems as $id=>$item) {
                        $product = $item['product'];
                        $qty = $item['qty'];
                        $totalCartItems += $product['price'] * $qty;
                        $cntCartItems++;
                    }
                ?>
                <a href="/cart"><span class="icon-shopping-cart"></span> <?php echo $cntCartItems; ?> Item(s) - <span class="badge badge-warning"> $<?php echo number_format($totalCartItems,2);?></span></a>
            </div>
            
            
        </div>
    </header>
    
<!-- 
Body Section 
-->
    <div class="row">
        <?php if(empty($noSidebar)): ?>
        <div id="sidebar" class="span3">
            <div class="well well-small">
                <?php include 'categories.phtml'; ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="<?php echo empty($noSidebar)? 'span9':'span12';?>">
            <?php include 'breadcrumb.phtml'; ?>
            <?php if(!empty($flashMessage)): ?>
                <div class="alert alert-block">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                   <?php echo nl2br(h($flashMessage));?>
                </div>
            <?php endif; ?>
    
<?php
    echo $content;
?>

        </div>
    </div>
    <?php if(0): ?>
    <!-- 
    Brands 
    -->
    <section class="our_client">
        <hr class="soften"/>
        <h4 class="title cntr"><span class="text">Manufactures</span></h4>
        <hr class="soften"/>
        <?php include 'manufacturers.phtml'; ?>
    </section>
    <?php endif; ?>
    

    <!--
    Footer
    -->
    <footer class="footer">
        <div class="row-fluid">
            <div class="span2">
                <h5>Your Account</h5>
                <a href="#">YOUR ACCOUNT</a><br>
                <a href="#">PERSONAL INFORMATION</a><br>
                <a href="#">ADDRESSES</a><br>
                <a href="#">DISCOUNT</a><br>
                <a href="#">ORDER HISTORY</a><br>
            </div>
            <div class="span2">
                <h5>Iinformation</h5>
                <a href="contact.html">CONTACT</a><br>
                <a href="#">SITEMAP</a><br>
                <a href="#">LEGAL NOTICE</a><br>
                <a href="#">TERMS AND CONDITIONS</a><br>
                <a href="#">ABOUT US</a><br>
            </div>
            <div class="span2">
                <h5>Our Offer</h5>
                <a href="#">NEW PRODUCTS</a> <br>
                <a href="#">TOP SELLERS</a><br>
                <a href="#">SPECIALS</a><br>
                <a href="#">MANUFACTURERS</a><br>
                <a href="#">SUPPLIERS</a> <br/>
            </div>
            <div class="span6">
                <h5><a href="https://cointelegraph.com/">CoinTelegprah news</a></h5>
                <?php
                        $content = file_get_contents("https://cointelegraph.com/editors_pick_rss");
                        $xml  = new SimpleXmlElement($content);
                        $rows = [];
                         foreach($xml->channel->item as $entry) {
                             $rows[] = [$entry->link,$entry->title];
                         }
                         shuffle($rows);
                         $result = array_slice($rows,0, 5);
                ?>
               <ul>
                   <?php foreach($result as $row): ?>
                    <li><a href="<?php echo $row[0];?>" title="<?php echo h($row[1]);?>"><?php echo h($row[1]);?></a></li>
                   <?php endforeach;?>
               </ul>

            </div>
        </div>
    </footer>
</div><!-- /container -->


<div class="copyright">
    <div class="container">
        <p class="pull-right">
            <a href="#"><img src="/assets/img/maestro.png" alt="payment"></a>
            <a href="#"><img src="/assets/img/mc.png" alt="payment"></a>
            <a href="#"><img src="/assets/img/pp.png" alt="payment"></a>
            <a href="#"><img src="/assets/img/visa.png" alt="payment"></a>
            <a href="#"><img src="/assets/img/disc.png" alt="payment"></a>
        </p>
        <span>Copyright &copy; 2022<br><a href="/page/contact">COMPANY SRL</a></span>
    </div>
</div>

<a href="#" class="gotop"><i class="icon-double-angle-up"></i></a>
<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/js/jquery.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery.easing-1.3.min.js"></script>
<script src="/assets/js/jquery.scrollTo-1.4.3.1-min.js"></script>
<script src="/assets/js/shop.js"></script>
</body>
</html>

