<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Twitter Bootstrap shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <!-- Favicons -->
    <link rel="shortcut icon" href="/assets/ico/favicon.ico">
    <!-- Customize styles -->
    <link href="/assets/admin.css" rel="stylesheet"/>
</head>
<body>
<?php
    $curSection = $curSection ?? '';
?>
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link <?php echo $curSection=='dashboard' ? 'active':'';?>" href="/admin/dashboard">Dashboard</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?php echo $curSection=='order' ? 'active':'';?>" href="/admin/order/list">Orders</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?php echo $curSection=='product' ? 'active':'';?>" href="/admin/product/list">Products</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?php echo $curSection=='category' ? 'active':'';?>" href="/admin/category/list">Categories</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/user/logout">logout</a>
    </li>
</ul>

<?php if(!empty($flashMessage)): ?>
    <div class="alert alert-danger" role="alert" style="position:absolute;right:3px;top:3px;">
        <?php echo nl2br(h($flashMessage)); ?>
        [<a href="#" onclick="this.parentNode.parentNode.removeChild(this.parentNode);return false;">close</a>]
    </div>
<?php endif; ?>
<?php if(!empty($title)): ?>
<h3><?php echo h($title);?></h3>
<hr>
<?php endif; ?>
<?php
    /** @var string $content */
    echo $content;
?>


<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/js/jquery.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>

</body>
</html>

