<?php
/** 
 * @var string $title
 * @var array $product  
 */
?>

<div class="container">
    <h3><?php echo h($title);?></h3>
    <form action="/admin/product/<?php echo empty($product['id'])?'new':"edit/{$product['id']}";?>" method="post" enctype="multipart/form-data">
        <div class="form-group row mb-1">
            <label for="productName" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="productName" placeholder="Product name" name="product[name]" value="<?php echo h($product['name']);?>">
            </div>
        </div>
        <div class="form-group row mb-1">
            <label for="productPrice" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-1">
                <input type="text" class="form-control" id="productPrice" placeholder="Price" name="product[price]" value="<?php echo h($product['price']);?>">
            </div>
        </div>
        <div class="form-group row mb-1">
            <label for="productDesc" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-5">
                <textarea class="form-control" id="productDesc" placeholder="Description" name="product[description]"><?php echo h($product['description']);?></textarea>
            </div>
        </div>
        <div class="form-group row mb-1">
            <label for="productCat" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-5">
                <select class="form-control" id="productCat" placeholder="Category" name="product[category_id]">
                    <option value = ""> --- </option>
                    <?php foreach($categories as $cat): ?>
                    <option value = "<?php echo $cat['id'] ?>" <?php echo $cat['id'] == $product["category_id"] ? "selected" : "" ?>> <?php echo h($cat['name']) ?> </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <?php if(!empty($product['image'])): ?>
        <div class="form-group row mb-1">
            <span class="col-sm-2 col-form-label">Image</span>
            <div class="col-sm-1">
                <img src="/assets/product/<?php echo trim($product['image'],"/");?>" alt="" width="50" >
                
            </div>
        </div>
        <input type="hidden" name="product[image]" value="<?php echo h($product['image']);?>">
        <?php endif; ?>
        <div class="form-group row mb-1">
            <label for="Image" class="col-sm-2 col-form-label">New Image</label>
            <div class="col-sm-1">
                <input type="file" class="form-control" id="image" placeholder="Image" name="image" value="">
            </div>
        </div>
        <div class="form-group row mb-1">
            <span class="col-sm-2"><a href="/admin/product/list">cancel</a></span>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Save product</button>
            </div>
        </div>
    </form>
</div>
